#!/usr/bin/env python
# pylint: disable=missing-docstring
# pylint: disable=too-few-public-methods

import logging
import sys
import argparse

from flock import node

class DefaultHelpParser(argparse.ArgumentParser):
    def error(self, message):
        sys.stderr.write('error: %s\n' % message)
        self.print_help()
        sys.exit(2)

def main():
    # Parse some params
    parser = DefaultHelpParser()
    parser.add_argument("-d", "--dir", help="Storage directory for apps (required)", required=True)
    args = parser.parse_args()

    # Logging system GO
    logging.basicConfig(level=logging.INFO)

    the_node = node.Node(args.dir, {})
    the_node.run()

main()


